submodules = [
    ["repos/rust", "src/doc/book"],
    ["repos/rust", "src/tools/cargo"],
    ["repos/rust", "src/doc/edition-guide"],
    ["repos/rust", "src/doc/embedded-book"],
    ["repos/rust", "src/doc/nomicon"],
    ["repos/rust", "src/doc/reference"],
]

[books.book]
path = "repos/rust/src/doc/book"
translations = []

[books.cargo]
path = "repos/rust/src/tools/cargo/src/doc"
translations = []

[books.edition-guide]
path = "repos/rust/src/doc/edition-guide"
translations = []

[books.embedded-book]
path = "repos/rust/src/doc/embedded-book"
translations = []

[books.nomicon]
path = "repos/rust/src/doc/nomicon"
translations = []

[books.reference]
path = "repos/rust/src/doc/reference"
translations = []

[books.rustc]
path = "repos/rust/src/doc/rustc"
translations = []

[books.rustdoc]
path = "repos/rust/src/doc/rustdoc"
translations = []
