submodules = [
    [
    'repos/rust',
    'src/doc/book',
],
    [
    'repos/rust',
    'src/tools/cargo',
],
    [
    'repos/rust',
    'src/doc/edition-guide',
],
    [
    'repos/rust',
    'src/doc/embedded-book',
],
    [
    'repos/rust',
    'src/doc/nomicon',
],
    [
    'repos/rust',
    'src/doc/reference',
],
    ['repos/rust-cli'],
]
[books.book]
path = 'repos/rust/src/doc/book'

[[books.book.translations]]
id = 'ja'
name = '日本語'

[[books.book.translations]]
id = 'ru'
name = 'Русский'

[books.cargo]
path = 'repos/rust/src/tools/cargo/src/doc'

[[books.cargo.translations]]
id = 'ja'
name = '日本語'

[books.edition-guide]
path = 'repos/rust/src/doc/edition-guide'
translations = []

[books.embedded-book]
path = 'repos/rust/src/doc/embedded-book'
translations = []

[books.nomicon]
path = 'repos/rust/src/doc/nomicon'
translations = []

[books.reference]
path = 'repos/rust/src/doc/reference'
translations = []

[books.rust-cli]
path = 'repos/rust-cli'
translations = []

[books.rustc]
path = 'repos/rust/src/doc/rustc'
translations = []

[books.rustdoc]
path = 'repos/rust/src/doc/rustdoc'
translations = []
