[books.book]
translations = [
    { id = "ja", name = "日本語" },
]

[books.edition-guide]
translations = [
    { id = "ja", name = "日本語" },
]

[books.embedded-book]
translations = [
    { id = "ja", name = "日本語" },
]

[books.nomicon]
translations = [
    { id = "ja", name = "日本語" },
]

[books.reference]
translations = [
    { id = "ja", name = "日本語" },
]
