[books.book]
translations = []

[books.cargo]
path = "src/doc"
translations = []

[books.edition-guide]
translations = []

[books.embedded-book]
translations = []

[books.nomicon]
translations = []

[books.reference]
translations = []
