name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: beta
      - uses: Swatinem/rust-cache@v2
      - name: Build document
        run: |
          cargo run --release -- build
      - name: Build site
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_DIR: ./site
          BUILD_ONLY: true
      - run: |
          cp -rv site/public/* build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: rust-lang-translations.org
          publish_dir: ./build
