name: Deploy

on:
  push:
    branches:
      - master

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: beta
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          cargo run --release -- build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: doc.rust-lang-translations.org
          publish_dir: ./build
