name: Submodule Update

on:
  schedule:
  - cron: 0 0 * * SUN
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: |
          git submodule update --remote
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update submodules"
          add: 'repos'
